<!DOCTYPE html>
<html>
<head>
    <title>Laporan Master Data Indikator</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #444; padding-bottom: 10px; margin-bottom: 20px; }
        .header h2 { margin: 0; color: #1a1035; text-transform: uppercase; }
        .header p { margin: 5px 0 0; font-size: 12px; color: #666; }
        .info { margin-bottom: 20px; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; table-layout: fixed; }
        th { background-color: #1a1035; color: white; padding: 10px; font-size: 11px; text-transform: uppercase; border: 1px solid #ddd; }
        td { padding: 8px; font-size: 10px; border: 1px solid #ddd; word-wrap: break-word; }
        .text-center { text-align: center; }
        .badge-id { font-family: monospace; font-weight: bold; color: #4B0082; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; color: #aaa; padding-top: 10px; border-top: 1px solid #eee; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Laporan Master Data Indikator</h2>
        <p>Sistem Informasi Pelaporan Kinerja - Kecamatan Driyorejo</p>
    </div>

    <div class="info">
        Tanggal Cetak: {{ date('d-m-Y H:i') }}<br>
        Dicetak Oleh: {{ Auth::user()->name }}
    </div>

    <table>
        <thead>
            <tr>
                <th width="8%">ID</th>
                <th width="10%">Klaster</th>
                <th width="10%">Program</th>
                <th width="42%">Nama Indikator</th>
                <th width="15%">Kategori Data</th>
                <th width="15%">Keterangan</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $i)
            <tr>
                <td class="text-center badge-id">#{{ str_pad($i->id_indikator, 3, '0', STR_PAD_LEFT) }}</td>
                <td class="text-center">#{{ str_pad($i->id_klaster, 3, '0', STR_PAD_LEFT) }}</td>
                <td class="text-center">#{{ str_pad($i->id_program, 3, '0', STR_PAD_LEFT) }}</td>
                <td>{{ $i->nama_indikator }}</td>
                <td class="text-center">{{ $i->program->klaster->nama_klaster ?? '-' }}</td>
                <td></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 30px; float: right; width: 250px; text-align: center;">
        <p style="font-size: 11px; margin-bottom: 60px;">Driyorejo, {{ date('d F Y') }}<br>Mengetahui,</p>
        <p style="font-size: 11px; font-weight: bold; border-bottom: 1px solid #000; display: inline-block; padding: 0 20px;">( ............................................ )</p>
        <p style="font-size: 10px; margin-top: 5px;">Kepala Instansi</p>
    </div>

    <div class="footer">
        Generated by SIP Driyorejo &copy; {{ date('Y') }}
    </div>
</body>
</html>
